/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas.gerencia;

import classesdao.SenhasDAO;
import java.security.SecureRandom;
import java.util.Base64;
import javax.swing.JOptionPane;
import senhas.Senhas;
import telas.telaGerenciador;
import usuario.Usuario;
import usuario.usuarioAtual;
import utilitarios.Gerenciador;

public class adicionarSenha extends javax.swing.JFrame {
    
        private boolean senhaVisivel = false;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adicionarSenha.class.getName());

    /**
     * Creates new form adicionarSenha
     */
    public adicionarSenha() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtServico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnVerSenha = new javax.swing.JButton();
        btnGerarSenha = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Serviço");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha");

        txtServico.setBackground(new java.awt.Color(153, 153, 153));
        txtServico.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Adicionar senha");

        txtSenha.setBackground(new java.awt.Color(153, 153, 153));
        txtSenha.setForeground(new java.awt.Color(0, 0, 0));

        btnVerSenha.setBackground(new java.awt.Color(153, 153, 153));
        btnVerSenha.setForeground(new java.awt.Color(255, 255, 255));
        btnVerSenha.setText("👁️");
        btnVerSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSenhaActionPerformed(evt);
            }
        });

        btnGerarSenha.setForeground(new java.awt.Color(255, 255, 255));
        btnGerarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Imagens/retorna.png"))); // NOI18N
        btnGerarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarSenhaActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(0, 0, 0));
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtServico, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVerSenha)
                                .addGap(18, 18, 18)
                                .addComponent(btnGerarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtServico, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGerarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVerSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarSenhaActionPerformed
    
        
       String resposta = JOptionPane.showInputDialog(null, "Informe o tamanho da senha (6 a 32 caracteres)", "Tamanho da senha", 1);
       try {
       int tamanho = Integer.parseInt(resposta);
       
       if(tamanho < 6 || tamanho > 32) {
           JOptionPane.showMessageDialog(null, "Tamanho invalido");
       }
       else {
           Gerenciador g = new Gerenciador();
        String senhaGerada = g.gerarSenha(tamanho);
        txtSenha.setText(senhaGerada);
       }
       
               } catch(Exception ex) {
                   JOptionPane.showMessageDialog(null, "Insira apenas valores inteiros");
                   
               }
    }//GEN-LAST:event_btnGerarSenhaActionPerformed

    private void btnVerSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSenhaActionPerformed
        
    if(senhaVisivel) {
        txtSenha.setEchoChar('*'); //Se a senha for visivel e usuario apertar o botão, esconde a senha
        senhaVisivel = false; //Deixa a variavel de controle como senha não visivel
        txtSenha.requestFocus(); //Retorna para o campo senha
    }
    
    else {
        txtSenha.setEchoChar((char)0); //Torna a senha visivel
        senhaVisivel = true;
        txtSenha.requestFocus();
    }
    
        
    }//GEN-LAST:event_btnVerSenhaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       
        String servico = txtServico.getText();
        char[] caracteres = txtSenha.getPassword();
        String senha = ""; 
       
        for(char c : caracteres) {
            senha += c;
        }
        
        if(servico.isEmpty() || senha.isEmpty()) {
            telaGerenciador tg = new telaGerenciador();
            tg.setVisible(true);
            dispose();
        }
        else {
            
            
           byte[] iv = new byte[12];
        
         SecureRandom sr = new SecureRandom();  //Sorteia um IV aleatorio e unico por senha
         sr.nextBytes(iv);
            
        
        Gerenciador g = new Gerenciador();
        
        
        
        String senhaCripto = g.criptografar(senha, usuarioAtual.getChaveAES(), iv); //Criptografa a senha informada
        String ivEncode = Base64.getEncoder().encodeToString(iv); //Encoda o iv em base64
            
            Senhas senhaUser = new Senhas();
            Usuario user = usuarioAtual.getUser(); //Recebe o usuario atual na memoria
            
            senhaUser.setServico(servico); //Salva o serviço da senha da instancia
            senhaUser.setSenhaCriptografada(senhaCripto); //Adiciona a senha criptografada em Senhas
            senhaUser.setIv(ivEncode); //Adiciona o IV em senhas
            senhaUser.setIdUsuario(user.getIdUsuario()); //Seta o id do usuario
            
            SenhasDAO sdao = new SenhasDAO();
            sdao.addSenha(senhaUser);
            
            telaGerenciador tg = new telaGerenciador();
            tg.setVisible(true);
            dispose();
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adicionarSenha().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarSenha;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVerSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtServico;
    // End of variables declaration//GEN-END:variables
}
