
package telas.gerencia;

import classesdao.SenhasDAO;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.List;
import javax.swing.JOptionPane;
import senhas.Senhas;
import senhas.listaSen;
import telas.telaGerenciador;
import usuario.Usuario;
import usuario.usuarioAtual;
import utilitarios.Gerenciador;

public class editarSenha extends javax.swing.JFrame {
    
    private int idSenha;
    private String servicoInicial;
    private String senhaInicial;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(editarSenha.class.getName());

    private boolean senhaVisivel = false;
    private Gerenciador g = new Gerenciador();
    
    /**
     * Creates new form editarSenha
     * @param idSenha
     */
    public editarSenha(int idSenha) { //Recebe o id da senha na tela anterior
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        this.idSenha = idSenha;
        
        List<Senhas> senhas = listaSen.get();
        Senhas s = new Senhas();
        
        for(int i = 0; i < senhas.size(); i++) {
            
            if(idSenha == senhas.get(i).getIdSenha()) { //Se o id informado pelo usuario for o mesmo que o id da senha na lista
             s = senhas.get(i);                         //Recebe as informações da senha na posição
             break;
            }
        }
        
        //variavel s recebe a senha que o usuario clicou
        
        txtServico.setText(s.getServico()); //Coloca o serviço da senha no campo serviço
        txtSenha.setText(g.descriptografar(s.getSenhaCriptografada(), s.getIv())); //Adiciona a senha descriptografada no campo senha
        
       this.servicoInicial = txtServico.getText();
       this.senhaInicial = txtSenha.getText();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtServico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnGerarSenha = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txtSenha = new javax.swing.JTextField();
        btnExcluirSenha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Serviço");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha");

        txtServico.setBackground(new java.awt.Color(153, 153, 153));
        txtServico.setForeground(new java.awt.Color(0, 0, 0));
        txtServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServicoActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Editar senha");

        btnGerarSenha.setForeground(new java.awt.Color(255, 255, 255));
        btnGerarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Imagens/retorna.png"))); // NOI18N
        btnGerarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarSenhaActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(0, 0, 0));
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar alterações");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txtSenha.setBackground(new java.awt.Color(153, 153, 153));
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        btnExcluirSenha.setBackground(new java.awt.Color(0, 0, 0));
        btnExcluirSenha.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirSenha.setText("Excluir senha");
        btnExcluirSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(txtServico, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGerarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtServico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGerarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarSenhaActionPerformed

        String resposta = JOptionPane.showInputDialog(null, "Informe o tamanho da senha (6 a 32 caracteres)", "Tamanho da senha", 1);
        try {
            int tamanho = Integer.parseInt(resposta);

            if(tamanho < 6 || tamanho > 32) {
                JOptionPane.showMessageDialog(null, "Tamanho invalido");
            }
            else {
                Gerenciador g = new Gerenciador();
                String senhaGerada = g.gerarSenha(tamanho);
                txtSenha.setText(senhaGerada);
            }

        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Insira apenas valores inteiros");

        }
    }//GEN-LAST:event_btnGerarSenhaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

       String servicoAtual = txtServico.getText();
       String senhaAtual = txtSenha.getText();
      
       if(servicoAtual.equals(servicoInicial) && senhaAtual.equals(servicoInicial)) { //Se o serviço e a senha forem os mesmos
        telaGerenciador tg = new telaGerenciador();                                    //vplte para a tela gerenciador
        tg.setVisible(true);
        dispose();
       
       }

        if(servicoAtual.isEmpty() || senhaAtual.isEmpty()) { //se a senha ou serviço estiverem vazios, apenas volte a tela
            telaGerenciador tg = new telaGerenciador();
            tg.setVisible(true);
            dispose();
        }
        else {

            byte[] iv = new byte[12];

            SecureRandom sr = new SecureRandom();  //Sorteia um IV aleatorio e unico por senha
            sr.nextBytes(iv);

         

            String senhaCripto = g.criptografar(senhaAtual, usuarioAtual.getChaveAES(), iv); //Criptografa a senha informada
            String ivEncode = Base64.getEncoder().encodeToString(iv); //Encoda o iv em base64

            Senhas senhaUser = new Senhas();
            Usuario user = usuarioAtual.getUser(); //Recebe o usuario atual na memoria
            
            
            
            senhaUser.setIdSenha(idSenha); //Seta o mesmo id da senha
            senhaUser.setServico(servicoAtual); //Salva o serviço da senha da instancia
            senhaUser.setSenhaCriptografada(senhaCripto); //Adiciona a senha criptografada em Senhas
            senhaUser.setIv(ivEncode); //Adiciona o IV em senhas
            senhaUser.setIdUsuario(user.getIdUsuario()); //Seta o id do usuario
            
            SenhasDAO sdao = new SenhasDAO();
            sdao.editarSenha(senhaUser); //Faz o update da senha
                
            
            telaGerenciador tg = new telaGerenciador();
            tg.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServicoActionPerformed

    private void btnExcluirSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirSenhaActionPerformed
             
       try {
            String[] opcoes = {"Não","Sim"};
           
           int deletar = JOptionPane.showOptionDialog(rootPane, "Tem certeza que deseja excluir?", "Excluir senha",
                   JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
           
               if(deletar == 1) {
                  
                SenhasDAO sdao = new SenhasDAO();
                sdao.excluirSenha(idSenha);
                   telaGerenciador tg = new telaGerenciador();
            tg.setVisible(true);
            dispose();
            
               }
       } catch(Exception e) {
           JOptionPane.showMessageDialog(null, "Erro ao excluir senha");
       }
         
        
    }//GEN-LAST:event_btnExcluirSenhaActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirSenha;
    private javax.swing.JButton btnGerarSenha;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtServico;
    // End of variables declaration//GEN-END:variables
}
