/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classesdao.analisadorDAO;
import java.io.File;
import java.time.LocalDate;
import javax.swing.BoxLayout;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import usuario.usuarioAtual;
import utilitarios.AnalisadorArquivo;

public class telaAnalisadorArquivos extends javax.swing.JFrame {
    
    
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaAnalisadorArquivos.class.getName());

    /**
     * Creates new form telaAnalisadorArquivos
     */
    public telaAnalisadorArquivos() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
               
       
      
        
            }
        
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        pnpPrincipal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnpArquivos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Imagens/arquivoLupa.png"))); // NOI18N
        jLabel5.setText("  Analisar arquivos");

        btnVoltar.setBackground(new java.awt.Color(51, 0, 51));
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("< Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar)
                .addGap(415, 415, 415)
                .addComponent(jLabel5)
                .addContainerGap(520, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnpPrincipal.setBackground(new java.awt.Color(51, 0, 102));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Verifique a segurança de arquivos");

        pnpArquivos.setBackground(new java.awt.Color(52, 5, 120));
        pnpArquivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnpArquivosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnpArquivosMouseEntered(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("+");

        javax.swing.GroupLayout pnpArquivosLayout = new javax.swing.GroupLayout(pnpArquivos);
        pnpArquivos.setLayout(pnpArquivosLayout);
        pnpArquivosLayout.setHorizontalGroup(
            pnpArquivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnpArquivosLayout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(209, 209, 209))
        );
        pnpArquivosLayout.setVerticalGroup(
            pnpArquivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpArquivosLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel3)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Insira o arquivo a ser analisado");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tamanho máximo: 200mb");

        javax.swing.GroupLayout pnpPrincipalLayout = new javax.swing.GroupLayout(pnpPrincipal);
        pnpPrincipal.setLayout(pnpPrincipalLayout);
        pnpPrincipalLayout.setHorizontalGroup(
            pnpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnpPrincipalLayout.createSequentialGroup()
                .addContainerGap(368, Short.MAX_VALUE)
                .addComponent(pnpArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(393, 393, 393))
            .addGroup(pnpPrincipalLayout.createSequentialGroup()
                .addGroup(pnpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnpPrincipalLayout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addComponent(jLabel1))
                    .addGroup(pnpPrincipalLayout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(jLabel4))
                    .addGroup(pnpPrincipalLayout.createSequentialGroup()
                        .addGap(524, 524, 524)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnpPrincipalLayout.setVerticalGroup(
            pnpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpPrincipalLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(pnpArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        telaInicial ti = new telaInicial();
        ti.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void pnpArquivosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnpArquivosMouseEntered
     
    }//GEN-LAST:event_pnpArquivosMouseEntered

    private void pnpArquivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnpArquivosMouseClicked
              AnalisadorArquivo aq = new AnalisadorArquivo();
              JFileChooser escolheArquivo = new JFileChooser();
              
              int result = escolheArquivo.showOpenDialog(null);
             if(result != JFileChooser.APPROVE_OPTION) {
             return;
             }
                 
             File arquivo = escolheArquivo.getSelectedFile();
             
             long tamanhoMaximo = 200 * 1024 * 1024;
             long tamanhoArquivo = arquivo.length();
             
             if(tamanhoArquivo > tamanhoMaximo) {
                 JOptionPane.showMessageDialog(null, "Arquivo muito grande");
                 return;
             }             
             
               File arq = escolheArquivo.getSelectedFile();
        
          
          
           String extensao = "";
           if(arq.getName().contains(".")) {
        
           int inicio = arq.getName().indexOf(".")+1;
            int fim = arq.getName().length();
           
            extensao = arq.getName().substring(inicio, fim); //Recebe a extensão declarada do arquivo
            
         } else {
            extensao = "";  
           }  
            
            String tipoArquivo = "";
           if(extensao.isEmpty() && arq.canExecute()) { 
               tipoArquivo = "txt";      //Se o arquivo não tem extensão mas é um execultavel, adicione exe como tipo de arquivo
               
              
           } else if(extensao.isEmpty() && !arq.canExecute()) {
               tipoArquivo = "txt";
           }
           else {
               tipoArquivo = extensao;
           }
           
           
           String[] extensoesValidas = {"zip", "pdf", "exe", "png", "jpg", "docx", "txt"};
           boolean valido = false;
               for(String s : extensoesValidas) {
                
               if(s.equals(tipoArquivo)) {
                   valido = true;
                   break;
               } 
                   
               }
                 
               if(valido == false) {
                JOptionPane.showMessageDialog(null, "Extensão não suportada");
                return;
               }
               
               
               
                 int nivelRisco = aq.analisarArquivo(tipoArquivo, arq);
                 String resultado = "";
                  
        if(nivelRisco < 20) {
            resultado = "Arquivo aparentemente seguro";
        }
        else if(nivelRisco < 39) {
            resultado = "Arquivo suspeito";
        }
        if(nivelRisco >= 40) {
            resultado = "Arquivo potencialmente malicioso";
        }
                 
                   JPanel painel = new JPanel();
                   painel.setLayout(new BoxLayout(painel, BoxLayout.Y_AXIS));
                   
                   JLabel atencao = new JLabel();
                   JLabel Result = new JLabel();
                   atencao.setText("Resultado:");
                   atencao.setSize(jLabel4.getSize());
                   
                   Result.setText(resultado);
                   
                   analisadorDAO adao = new analisadorDAO();
                   adao.gerarRelatorioArquivo(arq.getName(), nivelRisco, LocalDate.now(), resultado, usuarioAtual.getUser().getIdUsuario());
                   
                   painel.add(atencao);
                   painel.add(Result);
                   
                  JOptionPane.showMessageDialog(null, painel);
          
                   
                   
           
    }//GEN-LAST:event_pnpArquivosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telaAnalisadorArquivos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnpArquivos;
    private javax.swing.JPanel pnpPrincipal;
    // End of variables declaration//GEN-END:variables
}
