/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classesdao.UsuarioDAO;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import usuario.Usuario;
import usuario.usuarioAtual;
import utilitarios.Bcrypt;

/**
 *
 * @author giovanny
 */
public class telaCadastroSenhaMestra extends javax.swing.JFrame {
    
    private boolean senhaVisivel = false;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaCadastroSenhaMestra.class.getName());

        public telaCadastroSenhaMestra() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSenhaMestra = new javax.swing.JPasswordField();
        txtConfirmSenhaMestra = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        btnCriarSenhaMestra = new javax.swing.JButton();
        btnVerSenha = new javax.swing.JButton();
        btnVerConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setText("Senha Mestra");

        jLabel2.setText("Crie uma senha mestra pra autenticar");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("Senha mestra");

        txtSenhaMestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaMestraActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel4.setText("Repetir senha mestra");

        btnCriarSenhaMestra.setBackground(new java.awt.Color(0, 0, 0));
        btnCriarSenhaMestra.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarSenhaMestra.setText("Criar senha mestra");
        btnCriarSenhaMestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarSenhaMestraActionPerformed(evt);
            }
        });

        btnVerSenha.setText("👁️");
        btnVerSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSenhaActionPerformed(evt);
            }
        });

        btnVerConfirm.setText("👁️");
        btnVerConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtConfirmSenhaMestra, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVerConfirm))
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSenhaMestra, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVerSenha))
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(btnCriarSenhaMestra, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(388, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(78, 78, 78)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenhaMestra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerSenha))
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfirmSenhaMestra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerConfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnCriarSenhaMestra, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSenhaActionPerformed
           
    if(senhaVisivel) {
        txtSenhaMestra.setEchoChar('*'); //Se a senha for visivel e usuario apertar o botão, esconde a senha
        senhaVisivel = false; //Deixa a variavel de controle como senha não visivel
        txtSenhaMestra.requestFocus(); //Retorna para o campo senha
    }
    
    else {
        txtSenhaMestra.setEchoChar((char)0); //Torna a senha visivel
        senhaVisivel = true;
        txtSenhaMestra.requestFocus();
    }
    
        
    }//GEN-LAST:event_btnVerSenhaActionPerformed

    private void btnVerConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerConfirmActionPerformed
               
    if(senhaVisivel) {
        txtConfirmSenhaMestra.setEchoChar('*'); //Se a senha for visivel e usuario apertar o botão, esconde a senha
        senhaVisivel = false; //Deixa a variavel de controle como senha não visivel
        txtConfirmSenhaMestra.requestFocus(); //Retorna para o campo senha
    }
    
    else {
        txtConfirmSenhaMestra.setEchoChar((char)0); //Torna a senha visivel
        senhaVisivel = true;
        txtConfirmSenhaMestra.requestFocus();
    }
    }//GEN-LAST:event_btnVerConfirmActionPerformed

    private void btnCriarSenhaMestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarSenhaMestraActionPerformed

        
        try {
        char[] caracteresSenha = txtSenhaMestra.getPassword();        
        char[] caracteresConfirmSenha = txtConfirmSenhaMestra.getPassword();
        String senhaMestra = "";
        String confirmSenhaMestra = "";
        
        for(char c : caracteresSenha) {
            senhaMestra += c;
        }
        
        for(char c : caracteresConfirmSenha) {
            confirmSenhaMestra += c;
        }
        
        if(senhaMestra.length() < 8) {
         JOptionPane.showMessageDialog(null, "A senha mestra deve ter pelo meno 8 caracteres");
         return;
        }
        
        if(senhaMestra.equals(confirmSenhaMestra)) {
            JOptionPane.showMessageDialog(null, "Senha mestra criada com sucesso");
            
            Usuario user = usuarioAtual.getUser(); //Recebe as informações de usuario do cadastro
            user.setSenhaMestraHash(Bcrypt.gerarHash(senhaMestra)); //Adiciona mais informações do usuario
            user.setDataCriacao(LocalDate.now());
            
            usuarioAtual.setUser(user); //Seta todas as informações no usuarioAtual
            
            UsuarioDAO userDao = new UsuarioDAO();
            
            userDao.inserir(user);  //Salva as informações de usuario no banco de dados
            
            
            
            
             telaLoginSenhaMestra tlsvm = new telaLoginSenhaMestra();
             tlsvm.setVisible(true);
             dispose();
             
        }
        else {
            JOptionPane.showMessageDialog(null, "As senhas não são iguais");
        }
        
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Erro: Usuario não existe");
            }
        
        
    }//GEN-LAST:event_btnCriarSenhaMestraActionPerformed

    private void txtSenhaMestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaMestraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaMestraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telaCadastroSenhaMestra().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarSenhaMestra;
    private javax.swing.JButton btnVerConfirm;
    private javax.swing.JButton btnVerSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtConfirmSenhaMestra;
    private javax.swing.JPasswordField txtSenhaMestra;
    // End of variables declaration//GEN-END:variables
}
