
package telas;

import classesdao.SenhasDAO;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import senhas.Senhas;
import senhas.listaSen;
import telas.gerencia.adicionarSenha;
import telas.gerencia.editarSenha;
import usuario.usuarioAtual;

public class telaGerenciador extends javax.swing.JFrame {
        
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaGerenciador.class.getName());
      List<Senhas> senhas = new ArrayList<>();
    /**
     * Creates new form telaGerenciador
     */
    public telaGerenciador() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
         
                
        passwordContainer.setLayout(new BoxLayout(passwordContainer, BoxLayout.Y_AXIS)); //Layout que organiza de forma vertical
        
        
        
        SenhasDAO sdao = new SenhasDAO();
        
        listaSen.set(sdao.buscar(usuarioAtual.getUser().getIdUsuario()));
        senhas = listaSen.get();
        
        if(!senhas.isEmpty()) { //Se houver ao menos 1 senha na lista de usuarios faça isso
            
            for(int i = 0; i < senhas.size(); i++) { //Percorre toda a lista de senhas do usuario
             
         Senhas senhaAtual = senhas.get(i); //Recebe a senha a ser adicionada na posição i
        
         String servico = senhaAtual.getServico(); //Recebe o serviço da senha na posição        
         JLabel service = new JLabel(servico);
         service.setFont(service.getFont().deriveFont(Font.BOLD));
         
         JLabel password = new JLabel("******");
         
         service.setFont(new Font("Arial", Font.BOLD, 18)); // serviço em negrito
         service.setForeground(lblSenhas.getForeground());
         password.setFont(new Font("Arial", Font.PLAIN, 16)); // senha normal
         password.setForeground(lblSenhas.getForeground());
         
         
         
         JPanel itemPanel = new JPanel();
           itemPanel.setLayout(new BoxLayout(itemPanel, BoxLayout.Y_AXIS));
           itemPanel.setBackground(jPanel2.getBackground());

            itemPanel.setBorder(BorderFactory.createEmptyBorder(5, 5, 10, 5));
        
          itemPanel.add(service);
         
          itemPanel.add(password);
          
         itemPanel.setMaximumSize(itemPanel.getPreferredSize()); //Adiciona o tamanho minimo para não preencher toda tela com o painel
         itemPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
         
          itemPanel.addMouseListener(new MouseAdapter() { //Adiciona ação caso clique no painel
        
               @Override
    public void mouseEntered(MouseEvent e) {
        itemPanel.setBackground(new Color(200, 200, 255)); //Caso o usuario passe o mouse por cima do painel mude a cor para 
                                                           //demonstrar ao usuario que é clicavel
    }

    @Override
    public void mouseExited(MouseEvent e) { 
        itemPanel.setBackground(passwordContainer.getBackground()); //Volta a cor normal
    }
         
              
              
          @Override
            public void mouseClicked(MouseEvent e) {            
                
        editarSenha es = new editarSenha(Integer.parseInt(itemPanel.getName())); //Ao clicar no painel abra a tela 
                                           //editar senha, passando 
                                           //o id da senha como parametro, usando o nome do painel (que foi nomeado com o id)
              
            es.setVisible(true);
              
            }
              
          });
          itemPanel.setName(Integer.toString(senhaAtual.getIdSenha())); //Nomeia o painel com o valor do id da senha
          passwordContainer.add(itemPanel);                         //Assim, cada painel terá o valor de sua senha correspondente
           
          passwordContainer.revalidate();
          passwordContainer.repaint();  //Atualiza o painel principal caso uma nova senha seja adicionada
  
        
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblSenhas = new javax.swing.JLabel();
        btnNovaSenha = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        passwordContainer = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("("+senhas.size()+")");

        lblSenhas.setFont(new java.awt.Font("Liberation Sans", 2, 36)); // NOI18N
        lblSenhas.setForeground(new java.awt.Color(255, 255, 255));
        lblSenhas.setText("Suas senhas");

        btnNovaSenha.setBackground(new java.awt.Color(0, 0, 153));
        btnNovaSenha.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaSenha.setText("+ Nova senha");
        btnNovaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaSenhaActionPerformed(evt);
            }
        });

        passwordContainer.setBackground(new java.awt.Color(51, 0, 102));

        javax.swing.GroupLayout passwordContainerLayout = new javax.swing.GroupLayout(passwordContainer);
        passwordContainer.setLayout(passwordContainerLayout);
        passwordContainerLayout.setHorizontalGroup(
            passwordContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1214, Short.MAX_VALUE)
        );
        passwordContainerLayout.setVerticalGroup(
            passwordContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(passwordContainer);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSenhas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblSenhas))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1))
        );

        jPanel5.setBackground(new java.awt.Color(51, 0, 51));

        jLabel30.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Imagens/cadeado.png"))); // NOI18N
        jLabel30.setText("Gerenciador de senhas");

        btnVoltar.setBackground(new java.awt.Color(51, 0, 51));
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("< Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar)
                .addGap(385, 385, 385)
                .addComponent(jLabel30)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnVoltar))
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        telaInicial ti = new telaInicial();
        ti.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnNovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaSenhaActionPerformed
          
        adicionarSenha as = new adicionarSenha();
        as.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNovaSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telaGerenciador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovaSenha;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSenhas;
    private javax.swing.JPanel passwordContainer;
    // End of variables declaration//GEN-END:variables
}
