/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classesdao.UsuarioDAO;
import java.util.Base64;
import javax.swing.JOptionPane;
import usuario.Usuario;
import usuario.usuarioAtual;
import utilitarios.Bcrypt;
import utilitarios.Gerenciador;


public class telaLoginSenhaMestra extends javax.swing.JFrame {
    
      private boolean senhaVisivel = false;
      private int tentativas = 5;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaLoginSenhaMestra.class.getName());

    /**
     * Creates new form telaLoginSenhaMestra
     */
    public telaLoginSenhaMestra() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        lblIncorreto.setVisible(false);
        lblTentativas.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSenhaMestra = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        btnVerSenhaMestra = new javax.swing.JButton();
        lblTentativas = new javax.swing.JLabel();
        lblIncorreto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setText("Senha Mestra");

        jLabel2.setText("Digite a senha mestra pra continuar");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("Senha mestra");

        txtSenhaMestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaMestraActionPerformed(evt);
            }
        });

        btnEntrar.setBackground(new java.awt.Color(0, 0, 0));
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnVerSenhaMestra.setText("👁️");
        btnVerSenhaMestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSenhaMestraActionPerformed(evt);
            }
        });

        lblTentativas.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTentativas.setForeground(new java.awt.Color(255, 0, 51));
        lblTentativas.setText("Tentativas restantes: "+ tentativas);

        lblIncorreto.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblIncorreto.setForeground(new java.awt.Color(255, 0, 51));
        lblIncorreto.setText("Senha mestra incorreta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(452, 452, 452)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSenhaMestra, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVerSenhaMestra))
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(482, 482, 482)
                        .addComponent(lblTentativas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(lblIncorreto)))
                .addContainerGap(443, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblIncorreto)
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenhaMestra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerSenhaMestra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTentativas)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSenhaMestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaMestraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaMestraActionPerformed

    private void btnVerSenhaMestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSenhaMestraActionPerformed
             
    if(senhaVisivel) {
        txtSenhaMestra.setEchoChar('*'); //Se a senha for visivel e usuario apertar o botão, esconde a senha
        senhaVisivel = false; //Deixa a variavel de controle como senha não visivel
        txtSenhaMestra.requestFocus(); //Retorna para o campo senha
    }
    
    else {
        txtSenhaMestra.setEchoChar((char)0); //Torna a senha visivel
        senhaVisivel = true;
        txtSenhaMestra.requestFocus();
    }
    
        
    }//GEN-LAST:event_btnVerSenhaMestraActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
      
        UsuarioDAO userDAO = new UsuarioDAO();
        
        Usuario user = userDAO.buscarAll(usuarioAtual.getUser().getIdUsuario());
          
        char[] caracteres = txtSenhaMestra.getPassword(); //recebe a senha digitada
        String senhaMestraDigitada = "";
        String hashSenhaMestra = user.getSenhaMestraHash();
        
        for(char c : caracteres) {
            senhaMestraDigitada += c;
        }
        
        
        if(Bcrypt.compararHash(senhaMestraDigitada, hashSenhaMestra)) { //Caso a senha digitada seja igual
         usuarioAtual.setUser(user);
            
          byte[] saltDecript = Base64.getDecoder().decode(user.getSalt());
            telaInicial ti = new telaInicial();
            
            Gerenciador gerenciador = new Gerenciador();
           String chave = gerenciador.gerarChave(senhaMestraDigitada, saltDecript);
           
            usuarioAtual.setChave(chave);
            ti.setVisible(true);
            dispose();
            
        }
        else {
            
          tentativas = tentativas - 1;
          
          if(tentativas == 0) {
              JOptionPane.showMessageDialog(null, "Muitas tentativas sem sucesso, tente novamente mais tarde");
              dispose();
          }       
          lblTentativas.setText("Tentativas restantes: "+ tentativas);
          lblIncorreto.setVisible(true);
          lblTentativas.setVisible(true);
       
          
        }
        
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telaLoginSenhaMestra().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnVerSenhaMestra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIncorreto;
    private javax.swing.JLabel lblTentativas;
    private javax.swing.JPasswordField txtSenhaMestra;
    // End of variables declaration//GEN-END:variables
}
